### ISSUE TITLE
Convert fleet unit from anonymous object to prototype

### ISSUE THREAD

**Issue by evgenkh82** [evgenkh82/JS_studying#6]
In addition to prototyping, move this functions to prototype:

- printFleetUnitShipList()
- printShipClassInfo
- printFleetUnitMinSpeed()

**Comment by evgenkh82** [comment]
what is it meaning "move this functions to prototype"?
we have prototype of ships and fleet unit, no?

**Comment by aleksei-khitev** [comment]
Yes, we have 2 prototypes.
However, `printFleetUnitMinSpeed()` is not in unit prototype.
Look at `toString()` prototype fleet function and move `printFleetUnitMinSpeed()` in the same way.

You already moved `printFleetUnitShipList()` to the `toString()` fleet unit prototype function and `printShipClassInfo()` to the `toString()` ship prototype function.

All you need is to move logic of `printFleetUnitMinSpeed()` to prototype function
