### ISSUE TITLE
Complete all exercises for Javascript  Loops topic

### ISSUE THREAD

**Issue by aleksei-khitev** [evgenkh82/JS_studying#9]
http://htmllab.ru/zadachi-po-javascript-conditional/

**Comment by evgenkh82** [comment]
there is some questions at point #8. in my textbook is written then construction (document.write()) is not using for now and outdated.
and I couldn't complete tasks with "*"(

**Comment by aleksei-khitev** [comment]
You can miss task 8.
What problem do you have with task 9?

**Comment by aleksei-khitev** [comment]
AS for task 10. it seems you need to use API to access document but we haven't read about it so you can miss this

**Comment by evgenkh82** [comment]
let size = 120;
let unit = "Kb";
let Кб = 1024;
let sizebite = size * Кб;
alert(sizebite);

**Comment by aleksei-khitev** [comment]
As far as I understand the task...
I have to show bytes, which you calculate from some `size` and `unit` values.

For example,
you have 5MB. Then you show `5*1024*1024=5242880 bytes` (`5*1024` for having KB and `*1024` for having bytes)
The same for GB and KB
